name = input('please input your name: ')
print('Hello ' + name + ', would you like to learn some python today?')
print('here is your name in upper case: ' + name.upper())
print('here is your name in lower case: ' + name.lower())
print('here is your name in title case: ' + name.title())
