places = ['paris', 'london', 'ireland', 'japan', 'greece']
print('Original order:')
print(places)
print('\nAlpha:')
print(sorted(places))
print('\nOriginal order:')
print(places)
print('\nReverse Alpha:')
print(sorted(places, reverse=True))
print('\nOriginal order:')
print(places)
places.reverse()
print('\nReverse non-alpha:')
print(places)
places.reverse()
print('\nOriginal order:')
print(places)
places.sort()
print('\nPermanent Alpha:')
print(places)
places.sort(reverse=True)
print('\nPermanent reverse alpha:')
print(places)
print(len(places))
